version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
  - dependency-name: pytest
    versions:
    - 6.2.1
