version = 1

test_patterns = ["/tests/*"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

pip install pytest pytest-cov
pytest --cov=./ --cov-report xml
curl https://deepsource.io/cli | sh
export DEEPSOURCE_DSN= ${{secrets.DNS}}
./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
