version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "setup.py",
  "tests/**",
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = "requirements.txt"

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 125
